# Session2
## numpy

In [2]:
# Since we call numpy functions a lot, we can shorten numpy as np
import numpy as np


In [3]:
print(np.exp(1.0)) #exponential function 
print(np.pi) #pi number
print(np.sqrt(4)) 

2.718281828459045
3.141592653589793
2.0


## Numpy array

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

print("mean:", arr.mean())

[1 2 3 4 5]
<class 'numpy.ndarray'>
mean: 3.0


In [13]:
arr = np.arange(2,20,3)
arr

array([ 2,  5,  8, 11, 14, 17])

In [14]:
# One thing that numpy arrays can do and ordinary lists cannot is applying mathematical operations directly to the
# array. Like this:
print(arr * 2)
print(arr + arr)
print(arr / 2.0)

[ 4 10 16 22 28 34]
[ 4 10 16 22 28 34]
[1.  2.5 4.  5.5 7.  8.5]


In [22]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [4]:
# we can also make matrices as well.
mat = np.arange(9).reshape((3, 3))
print(mat)
print("===============")
b = np.arange(10).reshape((5,2))
print(b)
print("===============")
b = np.arange(27).reshape((3,3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [25]:
# Getting the shape of a numpy array is really easy.
# For our matrix, the first element corresponds to the number of rows, and the second one is for the number of columns
print(mat.shape)
print(b.shape)

(3, 3)
(3, 3, 3)


In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [20]:
# access to elements
print(mat[1, 1])
print(mat[0, 0])
print(mat[2, 1])

4
0
7


In [5]:
print(mat)
print("="*40)
# Print the second element of each row
print(mat[:, 1])

# Print the first element of every column
print(mat[0, :])

# Print between the second and fourth elements of the first column
print(mat[1:3, 0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 4 7]
[0 1 2]
[3 6]


In [18]:

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"


2
77


In [24]:
# You can also apply the standard functions to matrices (they are numpy arrays after all)
# But here, you can also specify which axis you want to apply a function to.

mat = np.arange(6).reshape((2,3))
print(mat)
print("=================")
print(np.mean(mat)) # This gets the mean of the entire matrix
print("=================")
print(np.mean(mat, axis=0)) # This gets the mean of each column
print("=================")
print(np.mean(mat, axis=1)) # This gets the mean of each row

[[0 1 2]
 [3 4 5]]
2.5
[1.5 2.5 3.5]
[1. 4.]


In [19]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [20]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [21]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [7]:
# Say that you wanted to turn a matrix into just a one-dimensional vector. That's also pretty easy to do
# You use the ravel() function
print(mat)
print("=================")
ravled = mat.ravel()
print(ravled.shape)
print(ravled)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(9,)
[0 1 2 3 4 5 6 7 8]


In [9]:
# There are also some useful built-in functions for creating matrices
print("zeros matrices:")
print(np.zeros((5, 5)))
print("=================")

print(np.zeros((3,2,3)))

print("=================")
print("identity matrices:")
a = np.identity(5)
print(a)
print("=================")


# Create an array of ones
np.ones((3,4))

# Create an array with random values
np.random.random((2,2))

# Create an empty array
print(np.empty((3,2)))

# Create a full array
np.full((2,2),7)

# Create an array of evenly-spaced values
np.arange(10,25,5)
print("=================")

# Create an array of evenly-spaced values
np.linspace(0,2,9)

zeros matrices:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
identity matrices:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
#Create an array of ones
ones = np.ones((3,4))
print(ones)
print("=================")

# Create an array with random values
print (np.random.random((2,2)))
print("=================")

# Create an empty array
print(np.empty((3,2)))
print("=================")

# Create a full array
print(np.full((2,2),7))
print("=================")

# Create an array of evenly-spaced values
print(np.arange(10,25,5))
print("=================")

# Create an array of evenly-spaced values
print(np.linspace(0,2,9))
print("=================")

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.60511995 0.1217192 ]
 [0.08154723 0.98659915]]
[[1.47769106e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
[[7 7]
 [7 7]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### import from file


In [10]:
# Import your data
x, y, z = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=True)

In [11]:
print(type(x))
print(x)

<class 'numpy.ndarray'>
[0.2536 0.4839 0.1292 0.1781 0.6253]


In [12]:
# Import your data
x = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=False)

In [15]:
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(5, 3)


### Save NumPy Arrays

In [19]:
import numpy as np
x = np.arange(0.0,5.0,1.0)
np.savetxt('test.out', x.astype(np.int8), delimiter=',')

In [20]:
print(x)

[0. 1. 2. 3. 4.]
